SELECT DEPTNO,DEPTNAME,FLOOR FROM DEPARTMENT;
SELECT EMPNO,EMPNAME,TITLE,MANAGER,SALARY,DNO FROM EMPLOYEE;

SELECT USER FROM dual;

DELETE FROM EMPLOYEE WHERE EMPNO ='1005';

DELETE FROM DEPARTMENT WHERE DEPTNO ='7';